version: '3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: BetHouse_db
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BetHouse123456!
      - MSSQL_PID=Developer
  BetHouse.matches:
    container_name: BetHouse.matches
    build: ./src/BetHouse.Matches
    ports:
      - 5502:5502
  BetHouse.users:
    container_name: BetHouse.users
    build: ./src/BetHouse.Users
    ports:
      - 5501:5501
  BetHouse.bets:
    container_name: BetHouse.bets
    build: ./src/BetHouse.Bets
    ports:
      - 5503:5503
  BetHouse.odds:
    container_name: BetHouse.odds
    build: ./src/BetHouse.Odds
    ports:
      - 5504:5504